---
- name: Ansible list
  hosts: webserver
  vars:
  	oceans:
  	  - Indian
      - Atlantic
      - Pacific
      - Arctic
      - Southern Antarctic
  
  tasks:
    - name: List oceans
      debug:
      	msg: "The five oceans in the world are {{ oceans }}
